### ISSUE TITLE
Build and Upload docs to Azure

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/doc.websoft9.com#4]
Devops by action

* upload to Azure

**Comment by chendelin1982** [comment]
```
    - uses: bacongobbler/azure-blob-storage-upload@v2.0.0
      with:
        source_dir: build
        container_name: $web
        connection_string: ${{ secrets.Azure_blob }}
        #extra_args: '--destination-path ./'
        #overwrite: true
        sync: true
```

当前的写法导致每次同步会清空 storage 中其他方式上传的文件

**Comment by qiaofeng1227** [comment]
```
[root@iZj6c46sxkb44piei7ekgkZ ~]# az storage blob sync --help

Command
    az storage blob sync : Sync blobs recursively to a storage blob container.
        This command is in preview and under development. Reference and support levels:
        https://aka.ms/CLI_refstatus
Arguments
    --container -c [Required] : The sync destination container.
    --source -s    [Required] : The source file path to sync from.
    --auth-mode               : The mode in which to run the command. "login" mode will directly use
                                your login credentials for the authentication. The legacy "key" mode
                                will attempt to query for an account key if no authentication
                                parameters for the account are provided. Environment variable:
                                AZURE_STORAGE_AUTH_MODE.  Allowed values: key, login.
    --destination -d          : The destination path that will be prepended to the blob name.

Additional Flags Arguments
    --exclude-path            : Exclude these paths. This option does not support wildcard
                                characters (*). Checks relative path prefix. For example:
                                myFolder;myFolder/subDirName/file.pdf.
    --exclude-pattern         : Exclude these files where the name matches the pattern list. For
                                example: *.jpg;*.pdf;exactName. This option supports wildcard
                                characters (*).
    --include-pattern         : Include only these files where the name matches the pattern list.
                                For example: *.jpg;*.pdf;exactName. This option supports wildcard
                                characters (*).

Storage Account Arguments
    --account-key             : Storage account key. Must be used in conjunction with storage
                                account name. Environment variable: AZURE_STORAGE_KEY.
    --account-name            : Storage account name. Related environment variable:
                                AZURE_STORAGE_ACCOUNT. Must be used in conjunction with either
                                storage account key or a SAS token. If neither are present, the
                                command will try to query the storage account key using the
                                authenticated Azure account. If a large number of storage commands
                                are executed the API quota may be hit.
    --connection-string       : Storage account connection string. Environment variable:
                                AZURE_STORAGE_CONNECTION_STRING.
    --sas-token               : A Shared Access Signature (SAS). Must be used in conjunction with
                                storage account name. Environment variable: AZURE_STORAGE_SAS_TOKEN.

Global Arguments
    --debug                   : Increase logging verbosity to show all debug logs.
    --help -h                 : Show this help message and exit.
    --only-show-errors        : Only show errors, suppressing warnings.
    --output -o               : Output format.  Allowed values: json, jsonc, none, table, tsv, yaml,
                                yamlc.  Default: json.
    --query                   : JMESPath query string. See http://jmespath.org/ for more information
                                and examples.
    --subscription            : Name or ID of subscription. You can configure the default
                                subscription using `az account set -s NAME_OR_ID`.
    --verbose                 : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Sync a single blob to a container.
        az storage blob sync -c mycontainer -s "pat
```

**Comment by qiaofeng1227** [comment]
[azure-blob-storage](https://github.com/bacongobbler/azure-blob-storage-upload/blob/main/entrypoint.sh)

**Comment by chendelin1982** [comment]
solved
```
    - uses: bacongobbler/azure-blob-storage-upload@v2.0.0
      with:
        source_dir: build
        container_name: $web
        connection_string: ${{ secrets.Azure_blob }}
        extra_args: '--destination-path ./'
        overwrite: true
```
